# This is an autogenerated file. Do not edit. 
{
  description = "description here TODO from config";

  inputs = {

    euler-build.inputs.beam.follows = "beam";
    beam.inputs.euler-build.follows = "euler-build";
  };

  outputs = flakeInputs@{ self, euler-build, ... }:
    euler-build.mkEulerFlake {
      overlayPath = ./nix/overlay.nix;
      configPath = ./nix/config.nix;
      inputs = flakeInputs;
    };
}
