---
resolver: lts-15.13
extra-deps:
  - git: https://github.com/tathougies/beam 
    commit: ebbb8da05f0a4814aa741ffb2f5cbf6e57d73c29
    subdirs:
      - beam-core
# Problem: MacOS build failure
# >   Configuring mysql-0.1.7...
# >   setup: Missing dependencies on foreign libraries:
# >   * Missing (or bad) C libraries: ssl, crypto
# Possible solution:
# https://github.com/depressed-pho/HsOpenSSL/issues/41
# TODO: how to make it portable?
extra-include-dirs:
- /usr/local/opt/openssl/include
extra-lib-dirs:
- /usr/local/opt/openssl/lib
